include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
  exclude:
    - test/**.mocks.dart

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_final_locals
    - unnecessary_await_in_return
    - avoid_print
