// The part every generator shares: turning collected notices into the file
// `OpenSourceLicenses.registerBundled` reads, and refusing to write one it
// would reject. A list that fails at registration fails on the person's
// screen, on the platform nobody happened to open (FR-LIC-004).

import 'dart:convert';

/// Notices grouped by text — one entry per distinct text, names sorted, entries
/// sorted by their first name.
List<Map<String, Object>> noticesFrom(Map<String, Set<String>> byText) => [
      for (final e in byText.entries)
        {'packages': (e.value.toList()..sort()), 'license': e.key},
    ]..sort((a, b) => ((a['packages'] as List).first as String)
        .compareTo((b['packages'] as List).first as String));

/// Why [entries] would be refused at registration, or null when it would not.
/// Holds the same rule as `OpenSourceLicenses.parseBundled`.
String? noticeProblem(List<Map<String, Object>> entries) {
  for (final (i, e) in entries.indexed) {
    final packages = e['packages'];
    final text = e['license'];
    if (packages is! List ||
        packages.isEmpty ||
        packages.any((p) => p is! String || p.trim().isEmpty)) {
      final shown = jsonEncode(e);
      return '[$i]: a notice without a name — '
          '${shown.length > 80 ? '${shown.substring(0, 80)}…' : shown}';
    }
    if (text is! String || text.trim().isEmpty) {
      return '[$i] ${packages.join(', ')}: no license text';
    }
  }
  return null;
}

/// `(title, text)` for every pod a CocoaPods acknowledgements plist names.
/// The plist also carries a header and a footer (`Generated by CocoaPods`) in
/// the same shape as a pod — neither names a package, so neither is a notice.
List<(String, String)> podNoticesFrom(List<Map<String, dynamic>> specs) => [
      for (final s in specs)
        if (s['Title'] is String &&
            (s['Title'] as String).trim().isNotEmpty &&
            s['Title'] != 'Acknowledgements' &&
            s['FooterText'] is String &&
            (s['FooterText'] as String).trim().isNotEmpty)
          (s['Title'] as String, s['FooterText'] as String),
    ];
