import 'dart:convert';

import 'package:appplayer_core/appplayer_core.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../tool/licenses/notices.dart';

void main() {
  // The shape CocoaPods writes: a header, one row per pod, and a footer that
  // looks like a pod with an empty title.
  final acknowledgements = <Map<String, dynamic>>[
    {'Title': 'Acknowledgements', 'FooterText': 'This application makes use of…'},
    {'Title': 'FMDB', 'FooterText': 'MIT License\n\nCopyright (c) 2008 Flying Meat'},
    {'Title': '', 'FooterText': 'Generated by CocoaPods - https://cocoapods.org'},
  ];

  test('pod notices leave out the header and the footer', () {
    expect(podNoticesFrom(acknowledgements).map((n) => n.$1), ['FMDB']);
  });

  test('what a generator writes is what registration accepts', () {
    final byText = <String, Set<String>>{};
    for (final (name, text) in podNoticesFrom(acknowledgements)) {
      byText.putIfAbsent(text.trim(), () => {}).add(name);
    }
    final entries = noticesFrom(byText);
    expect(noticeProblem(entries), isNull);
    expect(OpenSourceLicenses.parseBundled(jsonEncode(entries)), hasLength(1));
  });

  // The generator holds the registration rule, so a list registration would
  // refuse is never written.
  for (final (why, entry) in <(String, Map<String, Object>)>[
    ('a blank name', {'packages': [''], 'license': 'x'}),
    ('no names', {'packages': <String>[], 'license': 'x'}),
    ('no text', {'packages': ['a'], 'license': ' '}),
  ]) {
    test('a list registration would refuse is not written: $why', () {
      expect(noticeProblem([entry]), isNotNull);
      expect(() => OpenSourceLicenses.parseBundled(jsonEncode([entry])),
          throwsFormatException);
    });
  }
}
